FROM node:16-alpine
EXPOSE 5000
WORKDIR /usr/src/app
COPY . .
RUN npm install && \
    npm run build && \
    npm install -g serve && \
    adduser -S appuser && \
    chown appuser .
USER appuser
CMD ["serve", "-s", "-l", "5000", "build"]